-- USERS TABLE
CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('ROLE_ADMIN', 'ROLE_STAFF', 'ROLE_USER') NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NUlL,
    CONSTRAINT PK_ID_USERS PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- CATEGORIES TABLE
CREATE TABLE categories (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    priority ENUM('LOW', 'MEDIUM', 'HIGH'),
    CONSTRAINT PK_ID_CAREGORY PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- TICKETS TABLE
CREATE TABLE tickets (
    id BIGINT NOT NULL AUTO_INCREMENT,
    category_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NUlL,
    CONSTRAINT PK_ID_TICKET PRIMARY KEY(id),
    CONSTRAINT FK_CATEGORY_ID_TICKET FOREIGN KEY(category_id) REFERENCES category(id),
    CONSTRAINT FK_USER_ID_TICKET FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;