-- USERS TABLE
CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('ROLE_ADMIN', 'ROLE_STAFF', 'ROLE_USER') NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NUlL,
    CONSTRAINT PK_ID_USERS PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;