-- USERS TABLE
CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('ROLE_ADMIN', 'ROLE_STAFF', 'ROLE_USER') NOT NULL DEFAULT 'ROLE_USER',
    status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NUlL,
    CONSTRAINT PK_ID_USERS PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- CATEGORIES TABLE
CREATE TABLE categories (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    priority ENUM('LOW', 'MEDIUM', 'HIGH'),
    CONSTRAINT PK_ID_CATEGORY PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- TICKETS TABLE
CREATE TABLE tickets (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NUlL,
    CONSTRAINT PK_ID_TICKET PRIMARY KEY(id),
    CONSTRAINT FK_USER_ID_TICKET FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT FK_CATEGORY_ID_TICKET FOREIGN KEY(category_id) REFERENCES categories(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- REPLIES TABLE
CREATE TABLE replies (
    id BIGINT NOT NULL AUTO_INCREMENT,
    ticket_id BIGINT NOT NULL,
    created_user_id BIGINT NOT NULL,
    responded_to_user_id BIGINT NOT NULL,
    parent_id BIGINT DEFAULT NULL,
    content TEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT PK_ID_REPLIES PRIMARY KEY(id),
    CONSTRAINT FK_TICKET_ID_REPLIES FOREIGN KEY(ticket_id) REFERENCES tickets(id),
    CONSTRAINT FK_CREATED_USER_ID_REPLIES FOREIGN KEY(created_user_id) REFERENCES users(id),
    CONSTRAINT FK_RESPONDED_TO_USER_ID_REPLIES FOREIGN KEY(responded_to_user_id) REFERENCES users(id),
    CONSTRAINT FK_PARENT_ID_REPLIES FOREIGN KEY(parent_id) REFERENCES replies(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;